# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='click_nums',
            new_name='click_num',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='fav_nums',
            new_name='fav_num',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goods_nums',
            new_name='goods_num',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='sold_nums',
            new_name='sold_num',
        ),
    ]
