# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180504_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='goods_num',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='购买数量'),
        ),
    ]
